### ISSUE TITLE
Missing GSON lib

### ISSUE THREAD

**Issue by SamBolduc** [storm345/ServerAssistantIssues#1]
Version : PaperSpigot 1.7.10
Error:

java.lang.NoClassDefFoundError: com/google/gson/Gson
        at org.stormdev.mc.servermonitor.main.a.d(ServerMonitorPremiumPlaceholderCheck.java:72) ~[?:?]
        at org.stormdev.mc.servermonitor.main.ServerMonitor.onEnable(ServerMonitor.java:31) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java) ~[faction.jar:git-PaperSpigot-unknown]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java) [faction.jar:git-PaperSpigot-unknown]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java) [faction.jar:git-PaperSpigot-unknown]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:273) [PlugMan.jar:?]
        at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114) [PlugMan.jar:?]
        at com.rylinaux.plugman.PlugManCommands.onCommand(PlugManCommands.java:100) [PlugMan.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java) [faction.jar:git-PaperSpigot-unknown]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java) [faction.jar:git-PaperSpigot-unknown]
        at com.massivecraft.massivelag.inject.command.MassiveLagCommandMap.dispatch(MassiveLagCommandMap.java:59) [MassiveLag.jar:?]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:760) [faction.jar:git-PaperSpigot-unknown]
        at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1220) [faction.jar:git-PaperSpigot-unknown]
        at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:1055) [faction.jar:git-PaperSpigot-unknown]
        at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28) [faction.jar:git-PaperSpigot-unknown]
        at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65) [faction.jar:git-PaperSpigot-unknown]
        at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:190) [faction.jar:git-PaperSpigot-unknown]
        at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [faction.jar:git-PaperSpigot-unknown]
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:807) [faction.jar:git-PaperSpigot-unknown]
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [faction.jar:git-PaperSpigot-unknown]
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:650) [faction.jar:git-PaperSpigot-unknown]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:556) [faction.jar:git-PaperSpigot-unknown]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [faction.jar:git-PaperSpigot-unknown]
Caused by: java.lang.ClassNotFoundException: com.google.gson.Gson
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java) ~[faction.jar:git-PaperSpigot-unknown]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java) ~[faction.jar:git-PaperSpigot-unknown]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_91]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_91]
        ... 23 more

**Comment by storm345** [comment]
You closed it because you fixed it? If so, what was the original cause? (Iirc spigot comes with gson available at runtime)

**Comment by storm345** [comment]
If the plugin needs to run on servers where gson isn't available in the expected package, I can include gson in my output jar to make it compatible.

**Comment by storm345** [comment]
ServerAssistant 1.0.3 has been released, this version should fix the issue mentioned as it now includes the missing dependency within itself. This allows for compatibility with versions of spigot where the dependency is in an abnormal location.
