### ISSUE TITLE
?

### ISSUE THREAD

**Issue by Mordiacci** [storm345/ServerAssistantIssues#2]
[02:37:20] [Server thread/INFO]: [ServerAssistant] Enabling ServerAssistant v1.0.8
[02:37:20] [Server thread/ERROR]: Error occurred while enabling ServerAssistant v1.0.8 (Is it up to date?)
java.lang.BootstrapMethodError: call site initialization exception
	at java.lang.invoke.CallSite.makeSite(CallSite.java:341) ~[?:1.8.0_151]
	at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:307) ~[?:1.8.0_151]
	at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297) ~[?:1.8.0_151]
	at org.stormdev.mc.servermonitor.main.ServerMonitor.onEnable(ServerMonitor.java:31) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[custom.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [custom.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [custom.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [custom.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [custom.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [custom.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [custom.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [custom.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [custom.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [custom.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.IllegalAccessException: no such method: org.stormdev.mc.servermonitor.main.a.d()boolean/invokeStatic
	at java.lang.invoke.MemberName.makeAccessException(MemberName.java:867) ~[?:1.8.0_151]
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1003) ~[?:1.8.0_151]
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1386) ~[?:1.8.0_151]
	at java.lang.invoke.MethodHandles$Lookup.findStatic(MethodHandles.java:780) ~[?:1.8.0_151]
	at org.stormdev.mc.servermonitor.main.ServerMonitor.揞嵖㺩濕犗(ServerMonitor.java) ~[?:?]
	at java.lang.invoke.CallSite.makeSite(CallSite.java:325) ~[?:1.8.0_151]
	... 14 more
Caused by: java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    org/stormdev/mc/servermonitor/main/a.d()Z @0: aload_0
  Reason:
    Type top (current frame, locals[0]) is not assignable to reference type
  Current Frame:
    bci: @0
    flags: { }
    locals: { }
    stack: { }
  Bytecode:
    0x0000000: 2ab6 0018 121a b600 1eac               

	at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:1.8.0_151]
	at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:975) ~[?:1.8.0_151]
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1000) ~[?:1.8.0_151]
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1386) ~[?:1.8.0_151]
	at java.lang.invoke.MethodHandles$Lookup.findStatic(MethodHandles.java:780) ~[?:1.8.0_151]
	at org.stormdev.mc.servermonitor.main.ServerMonitor.揞嵖㺩濕犗(ServerMonitor.java) ~[?:?]
	at java.lang.invoke.CallSite.makeSite(CallSite.java:325) ~[?:1.8.0_151]
	... 14 more

**Comment by storm345** [comment]
Hello, where did you obtain this copy of the plugin? It looks like it could be a problem with your copy of the plugin. Try redownloading the jar from spigot and see if this resolves your issue.

**Comment by storm345** [comment]
Could you also please message me your spigotmc.org username

**Comment by storm345** [comment]
And also please send me the broken JAR file so I can try and see what is wrong
