### ISSUE TITLE
Failure to start

### ISSUE THREAD

**Issue by Xonbie** [storm345/ServerAssistantIssues#7]
Just installed ServerAssistant and it will not start.

Relevant log 

[02:21:15 INFO]: [ServerAssistant] Enabling ServerAssistant v1.0.14*
[02:21:16 ERROR]: Error occurred while enabling ServerAssistant v1.0.14 (Is it up to date?)
java.lang.NoClassDefFoundError: javax/xml/ws/Holder
at org.stormdev.mc.servermonitor.main.a.d(ServerMonitorPremiumPlaceholderCheck.java:74) ~[?:?]
at org.stormdev.mc.servermonitor.main.ServerMonitor.onEnable(ServerMonitor.java:36) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-445]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-445]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-445]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-445]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-445]
at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:464) ~[patched_1.16.5.jar:git-Paper-445]
at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.5.jar:git-Paper-445]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:935) ~[patched_1.16.5.jar:git-Paper-445]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.5.jar:git-Paper-445]
at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: javax.xml.ws.Holder
at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:182) ~[patched_1.16.5.jar:git-Paper-445]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.5.jar:git-Paper-445]
at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
... 12 more
[02:21:16 INFO]: [ServerAssistant] Disabling ServerAssistant v1.0.14
[02:21:16 INFO]: [ServerAssistant] Terminating detectors...
[02:21:16 INFO]: [ServerAssistant] Server Assistant disabled!

**Comment by storm345** [comment]
Thanks for reaching out to me. I'll take a look later today and figure out
the issue.

Kind regards,
Eddie Brown

**Comment by storm345** [comment]
Okay looks like the issue was that you are using a newer version of the
Java runtime environment which no longer includes one of the bits of code
that the plugin expects to be there.

I have created an updated version which should fix this issue:
https://www.spigotmc.org/resources/server-assistant-automatic-issue-reporter-and-handler-report-errors-lag-and-crashes-with-cause.28664/
Please let me know if you have a problem.

Kind regards,
Eddie Brown

**Comment by Xonbie** [comment]
Can confirm plugin now loads and seems to be working correctly.

Thanks for the quick response and patch, wish all developers were as diligent as you.
